import { useEffect, useState } from 'react';
import './styles.css';

export const ScrollToTop = () => {
    const [showBtn, setShowBtn] = useState(false);
    const handleClickBtn = () => {
        document.documentElement.scrollTop = 0;
    }

    const handleScroll = () => {
        console.log(document.documentElement.scrollTop);

        setTimeout(() => {
            setShowBtn(document.documentElement.scrollTop > 0 ? true : false)
        }) 
    }

    useEffect(() => {
        document.addEventListener('scroll', handleScroll)
        return () => {
            document.removeEventListener('scroll', handleScroll)
        }
    }, [])

    return <div>
    <div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit metus. Duis fermentum ante et nunc rutrum, sed congue mi laoreet. Quisque ut malesuada leo, ac pellentesque turpis. Curabitur elementum lectus vitae sapien suscipit sagittis. Nam magna massa, pellentesque at felis a, lacinia maximus nibh. Sed tristique fermentum pulvinar. Fusce quis ultricies purus. Praesent bibendum erat et ipsum volutpat, eget tempor elit mattis.

Aenean ultrices, ligula sit amet condimentum sodales, felis ipsum lacinia urna, id mollis orci sem vitae mi. Vestibulum et pretium eros. Fusce quis hendrerit felis. Morbi et tortor in erat convallis luctus. Sed congue erat id urna molestie iaculis. Vivamus quis lectus imperdiet, tincidunt nisi vitae, aliquam magna. Pellentesque pretium mi mi. Aliquam ut purus at dolor gravida fringilla in quis tortor. Morbi eu vehicula turpis. Nullam at sem erat. Sed non ipsum vestibulum, pellentesque lorem aliquet, tincidunt leo. Aliquam sit amet imperdiet ex. Ut sit amet hendrerit lacus. Sed a lectus erat.

Aliquam mattis, magna in facilisis euismod, elit magna venenatis erat, vel fermentum ligula ligula elementum dui. Nam eu venenatis est. Sed posuere ultricies maximus. Nulla facilisi. Cras posuere dolor vestibulum, aliquam leo id, blandit nisl. Cras auctor nibh nunc, a tincidunt lacus mattis eu. Etiam auctor elit rutrum tincidunt consectetur. Vivamus facilisis tempus lacus et sodales. Nulla facilisi.

Sed eu varius lectus, non mollis ante. Morbi pulvinar cursus posuere. Phasellus faucibus libero quis enim scelerisque, at euismod lorem tristique. Cras tempus consequat maximus. Vestibulum pharetra feugiat libero, nec lobortis eros viverra ut. Donec ac purus vitae metus mollis fringilla. Morbi tempus facilisis aliquam. Sed auctor vitae tellus ut porttitor. Aenean at libero sed tortor auctor luctus et at arcu. Proin efficitur ultricies neque, ut tincidunt dolor scelerisque vel. Proin et porttitor neque. Duis pulvinar odio eget diam accumsan, quis ultricies magna dapibus. Pellentesque a tellus commodo, ullamcorper massa eu, accumsan mi. Fusce vel nisl venenatis, tincidunt lacus ac, congue augue. Donec nibh justo, vehicula at porttitor id, venenatis sit amet nibh.

Duis in massa ac est maximus vehicula. Duis ut dignissim nisi. Morbi luctus urna id venenatis feugiat. Phasellus porta augue diam, ac commodo metus venenatis at. Fusce commodo ipsum elit. Duis quis nunc sem. Pellentesque sit amet lacinia dui. Ut egestas metus nec eleifend fermentum. Aenean feugiat facilisis mi, vel venenatis sapien rhoncus id. Donec in pharetra ex, in cursus erat. Morbi mollis libero id consequat malesuada. Sed et augue facilisis, egestas dolor id, volutpat nisl. Suspendisse non imperdiet felis. Mauris laoreet in sapien vel laoreet.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit metus. Duis fermentum ante et nunc rutrum, sed congue mi laoreet. Quisque ut malesuada leo, ac pellentesque turpis. Curabitur elementum lectus vitae sapien suscipit sagittis. Nam magna massa, pellentesque at felis a, lacinia maximus nibh. Sed tristique fermentum pulvinar. Fusce quis ultricies purus. Praesent bibendum erat et ipsum volutpat, eget tempor elit mattis.

Aenean ultrices, ligula sit amet condimentum sodales, felis ipsum lacinia urna, id mollis orci sem vitae mi. Vestibulum et pretium eros. Fusce quis hendrerit felis. Morbi et tortor in erat convallis luctus. Sed congue erat id urna molestie iaculis. Vivamus quis lectus imperdiet, tincidunt nisi vitae, aliquam magna. Pellentesque pretium mi mi. Aliquam ut purus at dolor gravida fringilla in quis tortor. Morbi eu vehicula turpis. Nullam at sem erat. Sed non ipsum vestibulum, pellentesque lorem aliquet, tincidunt leo. Aliquam sit amet imperdiet ex. Ut sit amet hendrerit lacus. Sed a lectus erat.

Aliquam mattis, magna in facilisis euismod, elit magna venenatis erat, vel fermentum ligula ligula elementum dui. Nam eu venenatis est. Sed posuere ultricies maximus. Nulla facilisi. Cras posuere dolor vestibulum, aliquam leo id, blandit nisl. Cras auctor nibh nunc, a tincidunt lacus mattis eu. Etiam auctor elit rutrum tincidunt consectetur. Vivamus facilisis tempus lacus et sodales. Nulla facilisi.

Sed eu varius lectus, non mollis ante. Morbi pulvinar cursus posuere. Phasellus faucibus libero quis enim scelerisque, at euismod lorem tristique. Cras tempus consequat maximus. Vestibulum pharetra feugiat libero, nec lobortis eros viverra ut. Donec ac purus vitae metus mollis fringilla. Morbi tempus facilisis aliquam. Sed auctor vitae tellus ut porttitor. Aenean at libero sed tortor auctor luctus et at arcu. Proin efficitur ultricies neque, ut tincidunt dolor scelerisque vel. Proin et porttitor neque. Duis pulvinar odio eget diam accumsan, quis ultricies magna dapibus. Pellentesque a tellus commodo, ullamcorper massa eu, accumsan mi. Fusce vel nisl venenatis, tincidunt lacus ac, congue augue. Donec nibh justo, vehicula at porttitor id, venenatis sit amet nibh.

Duis in massa ac est maximus vehicula. Duis ut dignissim nisi. Morbi luctus urna id venenatis feugiat. Phasellus porta augue diam, ac commodo metus venenatis at. Fusce commodo ipsum elit. Duis quis nunc sem. Pellentesque sit amet lacinia dui. Ut egestas metus nec eleifend fermentum. Aenean feugiat facilisis mi, vel venenatis sapien rhoncus id. Donec in pharetra ex, in cursus erat. Morbi mollis libero id consequat malesuada. Sed et augue facilisis, egestas dolor id, volutpat nisl. Suspendisse non imperdiet felis. Mauris laoreet in sapien vel laoreet.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit metus. Duis fermentum ante et nunc rutrum, sed congue mi laoreet. Quisque ut malesuada leo, ac pellentesque turpis. Curabitur elementum lectus vitae sapien suscipit sagittis. Nam magna massa, pellentesque at felis a, lacinia maximus nibh. Sed tristique fermentum pulvinar. Fusce quis ultricies purus. Praesent bibendum erat et ipsum volutpat, eget tempor elit mattis.

Aenean ultrices, ligula sit amet condimentum sodales, felis ipsum lacinia urna, id mollis orci sem vitae mi. Vestibulum et pretium eros. Fusce quis hendrerit felis. Morbi et tortor in erat convallis luctus. Sed congue erat id urna molestie iaculis. Vivamus quis lectus imperdiet, tincidunt nisi vitae, aliquam magna. Pellentesque pretium mi mi. Aliquam ut purus at dolor gravida fringilla in quis tortor. Morbi eu vehicula turpis. Nullam at sem erat. Sed non ipsum vestibulum, pellentesque lorem aliquet, tincidunt leo. Aliquam sit amet imperdiet ex. Ut sit amet hendrerit lacus. Sed a lectus erat.

Aliquam mattis, magna in facilisis euismod, elit magna venenatis erat, vel fermentum ligula ligula elementum dui. Nam eu venenatis est. Sed posuere ultricies maximus. Nulla facilisi. Cras posuere dolor vestibulum, aliquam leo id, blandit nisl. Cras auctor nibh nunc, a tincidunt lacus mattis eu. Etiam auctor elit rutrum tincidunt consectetur. Vivamus facilisis tempus lacus et sodales. Nulla facilisi.

Sed eu varius lectus, non mollis ante. Morbi pulvinar cursus posuere. Phasellus faucibus libero quis enim scelerisque, at euismod lorem tristique. Cras tempus consequat maximus. Vestibulum pharetra feugiat libero, nec lobortis eros viverra ut. Donec ac purus vitae metus mollis fringilla. Morbi tempus facilisis aliquam. Sed auctor vitae tellus ut porttitor. Aenean at libero sed tortor auctor luctus et at arcu. Proin efficitur ultricies neque, ut tincidunt dolor scelerisque vel. Proin et porttitor neque. Duis pulvinar odio eget diam accumsan, quis ultricies magna dapibus. Pellentesque a tellus commodo, ullamcorper massa eu, accumsan mi. Fusce vel nisl venenatis, tincidunt lacus ac, congue augue. Donec nibh justo, vehicula at porttitor id, venenatis sit amet nibh.

Duis in massa ac est maximus vehicula. Duis ut dignissim nisi. Morbi luctus urna id venenatis feugiat. Phasellus porta augue diam, ac commodo metus venenatis at. Fusce commodo ipsum elit. Duis quis nunc sem. Pellentesque sit amet lacinia dui. Ut egestas metus nec eleifend fermentum. Aenean feugiat facilisis mi, vel venenatis sapien rhoncus id. Donec in pharetra ex, in cursus erat. Morbi mollis libero id consequat malesuada. Sed et augue facilisis, egestas dolor id, volutpat nisl. Suspendisse non imperdiet felis. Mauris laoreet in sapien vel laoreet.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit metus. Duis fermentum ante et nunc rutrum, sed congue mi laoreet. Quisque ut malesuada leo, ac pellentesque turpis. Curabitur elementum lectus vitae sapien suscipit sagittis. Nam magna massa, pellentesque at felis a, lacinia maximus nibh. Sed tristique fermentum pulvinar. Fusce quis ultricies purus. Praesent bibendum erat et ipsum volutpat, eget tempor elit mattis.

Aenean ultrices, ligula sit amet condimentum sodales, felis ipsum lacinia urna, id mollis orci sem vitae mi. Vestibulum et pretium eros. Fusce quis hendrerit felis. Morbi et tortor in erat convallis luctus. Sed congue erat id urna molestie iaculis. Vivamus quis lectus imperdiet, tincidunt nisi vitae, aliquam magna. Pellentesque pretium mi mi. Aliquam ut purus at dolor gravida fringilla in quis tortor. Morbi eu vehicula turpis. Nullam at sem erat. Sed non ipsum vestibulum, pellentesque lorem aliquet, tincidunt leo. Aliquam sit amet imperdiet ex. Ut sit amet hendrerit lacus. Sed a lectus erat.

Aliquam mattis, magna in facilisis euismod, elit magna venenatis erat, vel fermentum ligula ligula elementum dui. Nam eu venenatis est. Sed posuere ultricies maximus. Nulla facilisi. Cras posuere dolor vestibulum, aliquam leo id, blandit nisl. Cras auctor nibh nunc, a tincidunt lacus mattis eu. Etiam auctor elit rutrum tincidunt consectetur. Vivamus facilisis tempus lacus et sodales. Nulla facilisi.

Sed eu varius lectus, non mollis ante. Morbi pulvinar cursus posuere. Phasellus faucibus libero quis enim scelerisque, at euismod lorem tristique. Cras tempus consequat maximus. Vestibulum pharetra feugiat libero, nec lobortis eros viverra ut. Donec ac purus vitae metus mollis fringilla. Morbi tempus facilisis aliquam. Sed auctor vitae tellus ut porttitor. Aenean at libero sed tortor auctor luctus et at arcu. Proin efficitur ultricies neque, ut tincidunt dolor scelerisque vel. Proin et porttitor neque. Duis pulvinar odio eget diam accumsan, quis ultricies magna dapibus. Pellentesque a tellus commodo, ullamcorper massa eu, accumsan mi. Fusce vel nisl venenatis, tincidunt lacus ac, congue augue. Donec nibh justo, vehicula at porttitor id, venenatis sit amet nibh.

Duis in massa ac est maximus vehicula. Duis ut dignissim nisi. Morbi luctus urna id venenatis feugiat. Phasellus porta augue diam, ac commodo metus venenatis at. Fusce commodo ipsum elit. Duis quis nunc sem. Pellentesque sit amet lacinia dui. Ut egestas metus nec eleifend fermentum. Aenean feugiat facilisis mi, vel venenatis sapien rhoncus id. Donec in pharetra ex, in cursus erat. Morbi mollis libero id consequat malesuada. Sed et augue facilisis, egestas dolor id, volutpat nisl. Suspendisse non imperdiet felis. Mauris laoreet in sapien vel laoreet.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit metus. Duis fermentum ante et nunc rutrum, sed congue mi laoreet. Quisque ut malesuada leo, ac pellentesque turpis. Curabitur elementum lectus vitae sapien suscipit sagittis. Nam magna massa, pellentesque at felis a, lacinia maximus nibh. Sed tristique fermentum pulvinar. Fusce quis ultricies purus. Praesent bibendum erat et ipsum volutpat, eget tempor elit mattis.

Aenean ultrices, ligula sit amet condimentum sodales, felis ipsum lacinia urna, id mollis orci sem vitae mi. Vestibulum et pretium eros. Fusce quis hendrerit felis. Morbi et tortor in erat convallis luctus. Sed congue erat id urna molestie iaculis. Vivamus quis lectus imperdiet, tincidunt nisi vitae, aliquam magna. Pellentesque pretium mi mi. Aliquam ut purus at dolor gravida fringilla in quis tortor. Morbi eu vehicula turpis. Nullam at sem erat. Sed non ipsum vestibulum, pellentesque lorem aliquet, tincidunt leo. Aliquam sit amet imperdiet ex. Ut sit amet hendrerit lacus. Sed a lectus erat.

Aliquam mattis, magna in facilisis euismod, elit magna venenatis erat, vel fermentum ligula ligula elementum dui. Nam eu venenatis est. Sed posuere ultricies maximus. Nulla facilisi. Cras posuere dolor vestibulum, aliquam leo id, blandit nisl. Cras auctor nibh nunc, a tincidunt lacus mattis eu. Etiam auctor elit rutrum tincidunt consectetur. Vivamus facilisis tempus lacus et sodales. Nulla facilisi.

Sed eu varius lectus, non mollis ante. Morbi pulvinar cursus posuere. Phasellus faucibus libero quis enim scelerisque, at euismod lorem tristique. Cras tempus consequat maximus. Vestibulum pharetra feugiat libero, nec lobortis eros viverra ut. Donec ac purus vitae metus mollis fringilla. Morbi tempus facilisis aliquam. Sed auctor vitae tellus ut porttitor. Aenean at libero sed tortor auctor luctus et at arcu. Proin efficitur ultricies neque, ut tincidunt dolor scelerisque vel. Proin et porttitor neque. Duis pulvinar odio eget diam accumsan, quis ultricies magna dapibus. Pellentesque a tellus commodo, ullamcorper massa eu, accumsan mi. Fusce vel nisl venenatis, tincidunt lacus ac, congue augue. Donec nibh justo, vehicula at porttitor id, venenatis sit amet nibh.

Duis in massa ac est maximus vehicula. Duis ut dignissim nisi. Morbi luctus urna id venenatis feugiat. Phasellus porta augue diam, ac commodo metus venenatis at. Fusce commodo ipsum elit. Duis quis nunc sem. Pellentesque sit amet lacinia dui. Ut egestas metus nec eleifend fermentum. Aenean feugiat facilisis mi, vel venenatis sapien rhoncus id. Donec in pharetra ex, in cursus erat. Morbi mollis libero id consequat malesuada. Sed et augue facilisis, egestas dolor id, volutpat nisl. Suspendisse non imperdiet felis. Mauris laoreet in sapien vel laoreet.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit metus. Duis fermentum ante et nunc rutrum, sed congue mi laoreet. Quisque ut malesuada leo, ac pellentesque turpis. Curabitur elementum lectus vitae sapien suscipit sagittis. Nam magna massa, pellentesque at felis a, lacinia maximus nibh. Sed tristique fermentum pulvinar. Fusce quis ultricies purus. Praesent bibendum erat et ipsum volutpat, eget tempor elit mattis.

Aenean ultrices, ligula sit amet condimentum sodales, felis ipsum lacinia urna, id mollis orci sem vitae mi. Vestibulum et pretium eros. Fusce quis hendrerit felis. Morbi et tortor in erat convallis luctus. Sed congue erat id urna molestie iaculis. Vivamus quis lectus imperdiet, tincidunt nisi vitae, aliquam magna. Pellentesque pretium mi mi. Aliquam ut purus at dolor gravida fringilla in quis tortor. Morbi eu vehicula turpis. Nullam at sem erat. Sed non ipsum vestibulum, pellentesque lorem aliquet, tincidunt leo. Aliquam sit amet imperdiet ex. Ut sit amet hendrerit lacus. Sed a lectus erat.

Aliquam mattis, magna in facilisis euismod, elit magna venenatis erat, vel fermentum ligula ligula elementum dui. Nam eu venenatis est. Sed posuere ultricies maximus. Nulla facilisi. Cras posuere dolor vestibulum, aliquam leo id, blandit nisl. Cras auctor nibh nunc, a tincidunt lacus mattis eu. Etiam auctor elit rutrum tincidunt consectetur. Vivamus facilisis tempus lacus et sodales. Nulla facilisi.

Sed eu varius lectus, non mollis ante. Morbi pulvinar cursus posuere. Phasellus faucibus libero quis enim scelerisque, at euismod lorem tristique. Cras tempus consequat maximus. Vestibulum pharetra feugiat libero, nec lobortis eros viverra ut. Donec ac purus vitae metus mollis fringilla. Morbi tempus facilisis aliquam. Sed auctor vitae tellus ut porttitor. Aenean at libero sed tortor auctor luctus et at arcu. Proin efficitur ultricies neque, ut tincidunt dolor scelerisque vel. Proin et porttitor neque. Duis pulvinar odio eget diam accumsan, quis ultricies magna dapibus. Pellentesque a tellus commodo, ullamcorper massa eu, accumsan mi. Fusce vel nisl venenatis, tincidunt lacus ac, congue augue. Donec nibh justo, vehicula at porttitor id, venenatis sit amet nibh.

Duis in massa ac est maximus vehicula. Duis ut dignissim nisi. Morbi luctus urna id venenatis feugiat. Phasellus porta augue diam, ac commodo metus venenatis at. Fusce commodo ipsum elit. Duis quis nunc sem. Pellentesque sit amet lacinia dui. Ut egestas metus nec eleifend fermentum. Aenean feugiat facilisis mi, vel venenatis sapien rhoncus id. Donec in pharetra ex, in cursus erat. Morbi mollis libero id consequat malesuada. Sed et augue facilisis, egestas dolor id, volutpat nisl. Suspendisse non imperdiet felis. Mauris laoreet in sapien vel laoreet.
    </div>
    {showBtn && <button className="to-top-btn" onClick={handleClickBtn}>To top</button>}
  </div>
}